name = "MoistThermodynamics"
uuid = "0460cc1c-04d8-4f02-b57d-511136c80085"
authors = ["Charles Kawczynski <kawczynski.charles@gmail.com>"]
version = "0.1.0"

[deps]
CLIMAParameters = "6eacf6c3-8458-43b9-ae03-caf5306d3d53"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
RootSolvers = "7181ea78-2dcb-4de3-ab41-2b8ab5a31e74"

[compat]
CLIMAParameters = "0.1.0"
DocStringExtensions = "0.8.1"
RootSolvers = "0.2"
julia = "1.3"
