name = "Thermodynamics"
uuid = "b60c26fb-14c3-4610-9d3e-2d17fe7ff00c"
authors = ["Climate Modeling Alliance"]
version = "0.15.8"

[deps]
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"

Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
RootSolvers = "7181ea78-2dcb-4de3-ab41-2b8ab5a31e74"

[weakdeps]
ClimaParams = "5c42b081-d73a-476f-9059-fd94b934656c"

[extensions]
CreateParametersExt = "ClimaParams"

[compat]
ClimaParams = "1"
ForwardDiff = "1.0.1"

Random = "1"
RootSolvers = "0.4, 1"
julia = "1.6"
